#!/bin/sh

n=$(cat /sys/class/power_supply/BAT0/capacity)
m=$(cat /sys/class/power_supply/BAT1/capacity)

sum=$(($n+$m))
ans=$(($sum / 2))

if [ "$ans" -gt 97 ]; then
   icon="<fc=#8abeb7>   </fc>"
elif [ "$ans" -gt 75 ]; then
    icon="<fc=#8abeb7>   </fc>"
elif [ "$ans" -gt 50 ]; then
    icon="<fc=#b5bd68>   </fc>"
elif [ "$ans" -gt 25 ]; then
    icon="<fc=#de935f>   </fc>"
elif [ "$ans" -gt 10 ]; then
    icon="<fc=#cc6666>   </fc>"
else
    icon="<fc=#cc6666>   </fc>"
fi



echo "${icon}${ans} %"
